### PR TITLE
csys_style const var fix

### LINKED ISSUE #21: CONST Variable Bug
Some variables which should not be set to const are being set as type const..

image

### PR DESCRIPTION
**Pull request by SankalpMe**
csys_style const var is being assigned latter in other part of the code

### CODE REVIEW

**Comment by catruge** [comment]
@SankalpMe, thanks for finding that! I guess that I accidentally used `const` instead of `let` when going through the code. Do you think that this could be merged into a branch other than `master`? Maybe something named `fix-const-variables` or similar? I created one right now, and can switch the base for the pull request if you'd like me to.

**Review by catruge — APPROVED** [review]
Great!

**Comment by SankalpMe** [comment]
Oh sorry I merged to master . Should I revert?

**Comment by catruge** [comment]
@SankalpMe, no, don't worry about it. I'll branch `master` and then roll it back right now. Then, you can make your pull request from this repo to https://github.com/JonComo/anim.

**Comment by catruge** [comment]
Your fix should now be in the `const-variable-bugfix` branch and `master` should be rolled back. You can rename it if you want and then make your pull request to https://github.com/JonComo/anim.

**Comment by catruge** [comment]
It might be a good idea to make our own branch in this repository where we can merge all our changes into (maybe something named `development`). That way, we can test our changes more easily before creating pull requests to https://github.com/JonComo/anim.

**Comment by catruge** [comment]
Hello. I saw the pull request that you made on https://github.com/JonComo/anim/, so I added back your commit to the master branch and created a branch called `upstream-master` which should point to the commit before yours.

**Pull request merged**
